language: node_js
node_js:
    - 13

services:
    - docker

branches:
  only:
    - "master"

# Pre-testing install before testing
install:
    - echo "Nothing needs to install"

before_script:
    - echo "Nothing to testing"

script:
    - docker --version
    - docker build -t ci-demo .
    - docker tag ci-demo bhautikchudasama/ci-demo:latest

after_success:
    - docker login -u "$username" -p "$password"
    - docker push bhautikchudasama/ci-demo:latest

notifications:
  email:
    on_failure: change
    on_success: change